# Generated by Django 4.2.30 on 2026-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='patient_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
